import {
    CURRENT,
    FIELDS_ERROR,
    POST,
    RESET,
    RESET_PASSWORD,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const RESET_PASSWORD_CURRENT_RESET = `${RESET_PASSWORD}${CURRENT} ${RESET}`;
export const RESET_PASSWORD_CURRENT_UPDATE = `${RESET_PASSWORD}${CURRENT} ${UPDATE}`;
export const RESET_PASSWORD_POST = `${RESET_PASSWORD} ${POST}`;
export const RESET_PASSWORD_RESET = `${RESET_PASSWORD} ${RESET}`;
export const RESET_PASSWORD_FIELD_ERRORS_RESET = `${RESET_PASSWORD}${FIELDS_ERROR} ${RESET}`;
export const RESET_PASSWORD_FIELD_ERRORS_UPDATE = `${RESET_PASSWORD}${FIELDS_ERROR} ${UPDATE}`;
export const RESET_PASSWORD_STATUS_RESET = `${RESET_PASSWORD}${STATUS} ${RESET}`;
export const RESET_PASSWORD_STATUS_UPDATE = `${RESET_PASSWORD}${STATUS} ${UPDATE}`;
