import {
    ALL_IDS,
    BETA_KEYS,
    BY_ID,
    CURRENT,
    DELETE,
    END,
    GET,
    LOADING_DELETE,
    LOADING_POST,
    POST,
    PREVIOUS,
    REMOVE,
    RESET,
    SET,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const BETA_KEYS_ALL_IDS_REMOVE = `${BETA_KEYS}${ALL_IDS} ${REMOVE}`;
export const BETA_KEYS_ALL_IDS_RESET = `${BETA_KEYS}${ALL_IDS} ${RESET}`;
export const BETA_KEYS_ALL_IDS_SET = `${BETA_KEYS}${ALL_IDS} ${SET}`;
export const BETA_KEYS_BY_ID_REMOVE = `${BETA_KEYS}${BY_ID} ${REMOVE}`;
export const BETA_KEYS_BY_IDS_RESET = `${BETA_KEYS}${BY_ID} ${RESET}`;
export const BETA_KEYS_BY_IDS_SET = `${BETA_KEYS}${BY_ID} ${SET}`;
export const BETA_KEYS_CURRENT_RESET = `${BETA_KEYS}${CURRENT} ${RESET}`;
export const BETA_KEYS_CURRENT_UPDATE = `${BETA_KEYS}${CURRENT} ${UPDATE}`;
export const BETA_KEYS_DELETE = `${BETA_KEYS} ${DELETE}`;
export const BETA_KEYS_END_RESET = `${BETA_KEYS}${END} ${RESET}`;
export const BETA_KEYS_END_UPDATE = `${BETA_KEYS}${END} ${UPDATE}`;
export const BETA_KEYS_GET = `${BETA_KEYS} ${GET}`;
export const BETA_KEYS_LOADING_DELETE_RESET = `${BETA_KEYS}${LOADING_DELETE} ${RESET}`;
export const BETA_KEYS_LOADING_DELETE_UPDATE = `${BETA_KEYS}${LOADING_DELETE} ${UPDATE}`;
export const BETA_KEYS_LOADING_POST_RESET = `${BETA_KEYS}${LOADING_POST} ${RESET}`;
export const BETA_KEYS_LOADING_POST_UPDATE = `${BETA_KEYS}${LOADING_POST} ${UPDATE}`;
export const BETA_KEYS_POST = `${BETA_KEYS} ${POST}`;
export const BETA_KEYS_PREVIOUS_RESET = `${BETA_KEYS}${PREVIOUS} ${RESET}`;
export const BETA_KEYS_PREVIOUS_UPDATE = `${BETA_KEYS}${PREVIOUS} ${UPDATE}`;
export const BETA_KEYS_RESET = `${BETA_KEYS} ${RESET}`;
export const BETA_KEYS_STATUS_RESET = `${BETA_KEYS}${STATUS} ${RESET}`;
export const BETA_KEYS_SATUS_UPDATE = `${BETA_KEYS}${STATUS} ${UPDATE}`;
