import {
    ALL_IDS,
    BY_ID,
    CURRENT,
    DELETE,
    END,
    GALERIE_BLACKLISTS,
    GET,
    LOADING_DELETE,
    LOADING_POST,
    POST,
    PREVIOUS,
    REMOVE,
    RESET,
    SET,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const GALERIE_BLACKLISTS_ALL_IDS_REMOVE = `${GALERIE_BLACKLISTS}${ALL_IDS} ${REMOVE}`;
export const GALERIE_BLACKLISTS_ALL_IDS_RESET = `${GALERIE_BLACKLISTS}${ALL_IDS} ${RESET}`;
export const GALERIE_BLACKLISTS_ALL_IDS_SET = `${GALERIE_BLACKLISTS}${ALL_IDS} ${SET}`;
export const GALERIE_BLACKLISTS_BY_ID_REMOVE = `${GALERIE_BLACKLISTS}${BY_ID} ${REMOVE}`;
export const GALERIE_BLACKLISTS_BY_ID_RESET = `${GALERIE_BLACKLISTS}${BY_ID} ${RESET}`;
export const GALERIE_BLACKLISTS_BY_ID_SET = `${GALERIE_BLACKLISTS}${BY_ID} ${SET}`;
export const GALERIE_BLACKLISTS_BY_ID_UPDATE = `${GALERIE_BLACKLISTS}${BY_ID} ${UPDATE}`;
export const GALERIE_BLACKLISTS_CURRENT_RESET = `${GALERIE_BLACKLISTS}${CURRENT} ${RESET}`;
export const GALERIE_BLACKLISTS_CURRENT_UPDATE = `${GALERIE_BLACKLISTS}${CURRENT} ${UPDATE}`;
export const GALERIE_BLACKLISTS_DELETE = `${GALERIE_BLACKLISTS} ${DELETE}`;
export const GALERIE_BLACKLISTS_END_RESET = `${GALERIE_BLACKLISTS}${END} ${RESET}`;
export const GALERIE_BLACKLISTS_END_UPDATE = `${GALERIE_BLACKLISTS}${END} ${UPDATE}`;
export const GALERIE_BLACKLISTS_GET = `${GALERIE_BLACKLISTS} ${GET}`;
export const GALERIE_BLACKLISTS_LOADING_DELETE_RESET = `${GALERIE_BLACKLISTS}${LOADING_DELETE} ${RESET}`;
export const GALERIE_BLACKLISTS_LOADING_DELETE_UPDATE = `${GALERIE_BLACKLISTS}${LOADING_DELETE} ${UPDATE}`;
export const GALERIE_BLACKLISTS_LOADING_POST_RESET = `${GALERIE_BLACKLISTS}${LOADING_POST} ${RESET}`;
export const GALERIE_BLACKLISTS_LOADING_POST_UPDATE = `${GALERIE_BLACKLISTS}${LOADING_POST} ${UPDATE}`;
export const GALERIE_BLACKLISTS_POST = `${GALERIE_BLACKLISTS} ${POST}`;
export const GALERIE_BLACKLISTS_PREVIOUS_RESET = `${GALERIE_BLACKLISTS}${PREVIOUS} ${RESET}`;
export const GALERIE_BLACKLISTS_PREVIOUS_UPDATE = `${GALERIE_BLACKLISTS}${PREVIOUS} ${UPDATE}`;
export const GALERIE_BLACKLISTS_RESET = `${GALERIE_BLACKLISTS} ${RESET}`;
export const GALERIE_BLACKLISTS_STATUS_RESET = `${GALERIE_BLACKLISTS}${STATUS} ${RESET}`;
export const GALERIE_BLACKLISTS_STATUS_UPDATE = `${GALERIE_BLACKLISTS}${STATUS} ${UPDATE}`;
