import {
    CONFIRM_ACCOUNT,
    FIELDS_ERROR,
    POST,
    RESET,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const CONFIRM_ACCOUNT_FIELDS_ERROR_RESET = `${CONFIRM_ACCOUNT}${FIELDS_ERROR} ${RESET}`;
export const CONFIRM_ACCOUNT_FIELDS_ERROR_UPDATE = `${CONFIRM_ACCOUNT}${FIELDS_ERROR} ${UPDATE}`;
export const CONFIRM_ACCOUNT_POST = `${CONFIRM_ACCOUNT} ${POST}`;
export const CONFIRM_ACCOUNT_RESET = `${CONFIRM_ACCOUNT} ${RESET}`;
export const CONFIRM_ACCOUNT_STATUS_RESET = `${CONFIRM_ACCOUNT}${STATUS} ${RESET}`;
export const CONFIRM_ACCOUNT_STATUS_UPDATE = `${CONFIRM_ACCOUNT}${STATUS} ${UPDATE}`;
