import {
    ALL_IDS,
    BY_ID,
    CURRENT,
    DELETE,
    END,
    GET,
    INVITATIONS,
    LOADING_DELETE,
    LOADING_POST,
    POST,
    PREVIOUS,
    REMOVE,
    RESET,
    SET,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const INVITATIONS_ALL_IDS_REMOVE = `${INVITATIONS}${ALL_IDS} ${REMOVE}`;
export const INVITATIONS_ALL_IDS_RESET = `${INVITATIONS}${ALL_IDS} ${RESET}`;
export const INVITATIONS_ALL_IDS_SET = `${INVITATIONS}${ALL_IDS} ${SET}`;
export const INVITATIONS_BY_ID_REMOVE = `${INVITATIONS}${BY_ID} ${REMOVE}`;
export const INVITATIONS_BY_ID_RESET = `${INVITATIONS}${BY_ID} ${RESET}`;
export const INVITATIONS_BY_ID_SET = `${INVITATIONS}${BY_ID} ${SET}`;
export const INVITATIONS_CURRENT_RESET = `${INVITATIONS}${CURRENT} ${RESET}`;
export const INVITATIONS_CURRENT_UPDATE = `${INVITATIONS}${CURRENT} ${UPDATE}`;
export const INVITATIONS_END_RESET = `${INVITATIONS}${END} ${RESET}`;
export const INVITATIONS_END_UPDATE = `${INVITATIONS}${END} ${UPDATE}`;
export const INVITATIONS_DELETE = `${INVITATIONS} ${DELETE}`;
export const INVITATIONS_GET = `${INVITATIONS} ${GET}`;
export const INVITATIONS_LOADING_DELETE_RESET = `${INVITATIONS}${LOADING_DELETE} ${RESET}`;
export const INVITATIONS_LOADING_DELETE_UPDATE = `${INVITATIONS}${LOADING_DELETE} ${UPDATE}`;
export const INVITATIONS_LOADING_POST_RESET = `${INVITATIONS}${LOADING_POST} ${RESET}`;
export const INVITATIONS_LOADING_POST_UPDATE = `${INVITATIONS}${LOADING_POST} ${UPDATE}`;
export const INVITATIONS_POST = `${INVITATIONS} ${POST}`;
export const INVITATIONS_PREVIOUS_RESET = `${INVITATIONS}${PREVIOUS} ${RESET}`;
export const INVITATIONS_PREVIOUS_UPDATE = `${INVITATIONS}${PREVIOUS} ${UPDATE}`;
export const INVITATIONS_RESET = `${INVITATIONS} ${RESET}`;
export const INVITATIONS_STATUS_RESET = `${INVITATIONS}${STATUS} ${RESET}`;
export const INVITATIONS_STATUS_UPDATE = `${INVITATIONS}${STATUS} ${UPDATE}`;
