import {
    BY_ID,
    COMMENTS,
    DELETE,
    GET,
    POST,
    RESET,
    REMOVE,
    SET,
    LOADING_DELETE,
    UPDATE,
    LOADING_POST,
    CURRENT,
    ALL_IDS,
    STATUS,
    END,
    PREVIOUS,
} from '#store/genericActionTypes';

export const COMMENTS_ALL_IDS_RESET = `${COMMENTS}${ALL_IDS} ${RESET}`;
export const COMMENTS_ALL_IDS_UPDATE = `${COMMENTS}${ALL_IDS} ${UPDATE}`;
export const COMMENTS_BY_ID_REMOVE = `${COMMENTS}${BY_ID} ${REMOVE}`;
export const COMMENTS_BY_ID_RESET = `${COMMENTS}${BY_ID} ${RESET}`;
export const COMMENTS_BY_ID_SET = `${COMMENTS}${BY_ID} ${SET}`;
export const COMMENTS_BY_ID_UPDATE = `${COMMENTS}${BY_ID} ${UPDATE}`;
export const COMMENTS_CURRENT_RESET = `${COMMENTS}${CURRENT} ${RESET}`;
export const COMMENTS_CURRENT_UPDATE = `${COMMENTS}${CURRENT} ${UPDATE}`;
export const COMMENTS_DELETE = `${COMMENTS} ${DELETE}`;
export const COMMENTS_END_RESET = `${COMMENTS}${END} ${RESET}`;
export const COMMENTS_END_UPDATE = `${COMMENTS}${END} ${UPDATE}`;
export const COMMENTS_GET = `${COMMENTS} ${GET}`;
export const COMMENTS_LOADING_DELETE_RESET = `${COMMENTS}${LOADING_DELETE} ${RESET}`;
export const COMMENTS_LOADING_DELETE_UPDATE = `${COMMENTS}${LOADING_DELETE} ${UPDATE}`;
export const COMMENTS_LOADING_POST_RESET = `${COMMENTS}${LOADING_POST} ${RESET}`;
export const COMMENTS_LOADING_POST_UPDATE = `${COMMENTS}${LOADING_POST} ${UPDATE}`;
export const COMMENTS_POST = `${COMMENTS} ${POST}`;
export const COMMENTS_PREVIOUS_RESET = `${COMMENTS}${PREVIOUS} ${RESET}`;
export const COMMENTS_PREVIOUS_UPDATE = `${COMMENTS}${PREVIOUS} ${UPDATE}`;
export const COMMENTS_RESET = `${COMMENTS} ${RESET}`;
export const COMMENTS_STATUS_RESET = `${COMMENTS}${STATUS} ${RESET}`;
export const COMMENTS_STATUS_UPDATE = `${COMMENTS}${STATUS} ${UPDATE}`;
