import {
    FIELDS_ERROR,
    FORGOT_YOUR_PASSWORD,
    RESET,
    STATUS,
    UPDATE,
} from '#store/genericActionTypes';

export const FORGOT_YOUR_PASSWORD_FIELDS_ERROR_RESET = `${FORGOT_YOUR_PASSWORD}${FIELDS_ERROR} ${RESET}`;
export const FORGOT_YOUR_PASSWORD_FIELDS_ERROR_UPDATE = `${FORGOT_YOUR_PASSWORD}${FIELDS_ERROR} ${UPDATE}`;
export const FORGOT_YOUR_PASSWORD_RESET = `${FORGOT_YOUR_PASSWORD} ${RESET}`;
export const FORGOT_YOUR_PASSWORD_STATUS_RESET = `${FORGOT_YOUR_PASSWORD}${STATUS} ${RESET}`;
export const FORGOT_YOUR_PASSWORD_STATUS_UPDATE = `${FORGOT_YOUR_PASSWORD}${STATUS} ${UPDATE}`;
