import {
    ALL_IDS,
    BY_ID,
    CURRENT,
    DELETE,
    END,
    FIELDS_ERROR,
    GALERIES,
    GET,
    LOADING_DELETE,
    LOADING_POST,
    LOADING_PUT,
    POST,
    PREVIOUS,
    PUT,
    REMOVE,
    RESET,
    SET,
    STATUS_ID,
    STATUS_NAME,
    UPDATE,
} from '#store/genericActionTypes';

export const GALERIES_ALL_IDS_RESET = `${GALERIES}${ALL_IDS} ${RESET}`;
export const GALERIES_ALL_IDS_SET = `${GALERIES}${ALL_IDS} ${SET}`;
export const GALERIES_BY_ID_REMOVE = `${GALERIES}${BY_ID} ${REMOVE}`;
export const GALERIES_BY_ID_RESET = `${GALERIES}${BY_ID} ${RESET}`;
export const GALERIES_BY_ID_SET = `${GALERIES}${BY_ID} ${SET}`;
export const GALERIES_BY_UD_UPDATE = `${GALERIES}${BY_ID} ${UPDATE}`;
export const GALERIES_CURRENT_RESET = `${GALERIES}${CURRENT} ${RESET}`;
export const GALERIES_CURRENT_UPDATE = `${GALERIES}${CURRENT} ${UPDATE}`;
export const GALERIES_DELETE = `${GALERIES} ${DELETE}`;
export const GALERIES_END_RESET = `${GALERIES}${END} ${RESET}`;
export const GALERIES_END_UPDATE = `${GALERIES}${END} ${UPDATE}`;
export const GALERIES_FIELDS_ERROR_RESET = `${GALERIES}${FIELDS_ERROR} ${RESET}`;
export const GALERIES_FIELDS_ERROR_UPDATE = `${GALERIES}${FIELDS_ERROR} ${UPDATE}`;
export const GALERIES_FILTER_NAME_RESET = `${GALERIES}/filterName ${RESET}`;
export const GALERIES_FILTER_NAME_UPDATE = `${GALERIES}/filterName ${UPDATE}`;
export const GALERIES_GET = `${GALERIES} ${GET}`;
export const GALERIES_LOADING_DELETE_RESET = `${GALERIES}${LOADING_DELETE} ${RESET}`;
export const GALERIES_LOADING_DELETE_UPDATE = `${GALERIES}${LOADING_DELETE} ${UPDATE}`;
export const GALERIES_LOADING_POST_RESET = `${GALERIES}${LOADING_POST} ${RESET}`;
export const GALERIES_LOADING_POST_UPDATE = `${GALERIES}${LOADING_POST} ${UPDATE}`;
export const GALERIES_LOADING_PUT_RESET = `${GALERIES}${LOADING_PUT} ${RESET}`;
export const GALERIES_LOADING_PUT_UPDATE = `${GALERIES}${LOADING_PUT} ${UPDATE}`;
export const GALERIES_POST = `${GALERIES} ${POST}`;
export const GALERIES_PREVIOUS_RESET = `${GALERIES}${PREVIOUS} ${RESET}`;
export const GALERIES_PREVIOUS_UPDATE = `${GALERIES}${PREVIOUS} ${UPDATE}`;
export const GALERIES_PUT = `${GALERIES} ${PUT}`;
export const GALERIES_RESET = `${GALERIES} ${RESET}`;
export const GALERIES_STATUS_ID_RESET = `${GALERIES}${STATUS_ID} ${RESET}`;
export const GALERIES_STATUS_ID_UPDATE = `${GALERIES}${STATUS_ID} ${UPDATE}`;
export const GALERIES_STATUS_NAME_RESET = `${GALERIES}${STATUS_NAME} ${RESET}`;
export const GALERIES_STATUS_NAME_UPDATE = `${GALERIES}${STATUS_NAME} ${UPDATE}`;
